### ISSUE TITLE
TypeError: Cannot add property _extensionsEnabled, object is not extensible

### ISSUE THREAD

**Issue by the-simian** [apollographql/graphql-extensions#5]
I'm experiencing a strange issue

This line:
```
export function enableGraphQLExtensions(schema: GraphQLSchema & { _extensionsEnabled?: boolean }) {
```
Throws this: 
```
TypeError: Cannot add property _extensionsEnabled, object is not extensible
at Object.enableGraphQLExtensions (/app/node_modules/graphql-extensions/lib/index.js:105:31)
at doRunQuery (/app/node_modules/apollo-server-core/dist/runQuery.js:42:30)
at /app/node_modules/apollo-server-core/dist/runQuery.js:22:54
at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:606:10)
at Async._589ΓÇì.r.Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)
 at Async._589ΓÇì.r.Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
```

when I am using the `@std/esm` module and attempt to use the es6 'export syntax'

**Comment by martijnwalraven** [comment]
Hmmm, it seems your schema may have been marked with [Object.preventExtensions() ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions)? How are you creating your schema?

**Comment by the-simian** [comment]
I am using graphql-compose with the graphql-compose-mongoose plugin.

The strange thing is that it works just fine without the `@std/esm` / export syntax. using module.exports and the behavior is as expected.

Appreciate the insight, it would seem that somehow (perhaps in the transpilation process?) maybe an object is getting marked with this. I wonder if I should bring this up to JDD, the author of @std/esm ? Its still not immediately obvious to me why `module.exports` works well, but `export default` produces unexpected results.

i appreciate your thoughts thusfar, btw

**Comment by benjamn** [comment]
Hi @the-simian! This is a bit of a long shot, but is it possible that the `schema` object passed into that function is somehow a module namespace object, since `@std/esm` seals those [here](https://github.com/standard-things/esm/blob/aee96db6441b5be530e590029276470cde82c345/src/entry.js#L557)? In other words, do you have any code that does something like
```js
import * as schema from "./my/schema.js"
// and then later
enableGraphQLExtensions(schema)
```

**Comment by benjamn** [comment]
You would also get a namespace object back from a dynamic `import()`, so this kind of code could be the source of the problem:
```js
import("./my/schema").then(schema => {
  enableGraphQLExtensions(schema);
});
```
Instead, you probably want
```js
import("./my/schema").then(module => {
  enableGraphQLExtensions(module.default);
});
```

**Comment by the-simian** [comment]
@benjamn Hey! Thanks for popping in and giving your thoughts. Its great to hear from you, and your time thinking about this really appreciated!

So, offhand I think the [line you linked](https://github.com/standard-things/esm/blob/aee96db6441b5be530e590029276470cde82c345/src/entry.js#L557) might be what the issue is, because I can see it is clearly sealing objects. The act of extending the exported (and likely sealed) module is a problem somewhere inside the source for `graphql-compose`, which I am by no means an expert at, yet. I'll still try to fill in the blanks as best I can.

I'll show you basically what the usage is:
```js
import mongoose from 'mongoose';
import {composeWithMongoose} from 'graphql-compose-mongoose';
import { schemaComposer } from 'graphql-compose'; //this object will get decorated.
//make the User Type Composer
const userSchema = new mongoose.Schema({ email: String, name: String}); //a mongoose schema
const UserModel = mongoose.model('User', userSchema); //a mongoose model
const UserTC = composeWithMongoose(UserModel, {}); //converts mongoose model to the type-composer

// put stuff on the schema
schemaComposer.rootQuery().addFields({
  users: UserTC.getResolver('findMany')
});

//now output what will eventually be passed to the apollo server.

//this works.
module.exports =  schemaComposer.buildSchema();

//causes the error I posted
export default schemaComposer.buildSchema();
```

In other words, this does seem to resemble your first example, where I am importing, what I guess is a frozen object and then attempting to decorate it with the [`.addFields()`](https://github.com/graphql-compose/graphql-compose/blob/master/src/InputTypeComposer.js#L175) behavior, and then later call [`buildSchema`](https://github.com/graphql-compose/graphql-compose/blob/master/src/SchemaComposer.js#L62); I added links to what I believe is the relevant source code in the project.

I am guessing that in the background there could be some kind of stateful reference, so the enduser can build the schemaComposer and pass it around. maybe the author @nodkz would know.

The stack trace didn't point to his library directly, it pointed to, what seemed to be `graphql-extensions` in the `apollo-server-core`.

In any case, im not 100% sure where to open the issue on this, and I'm really happy you joined in. I know `@std/esm` is built atop your work, @benjamn , so I'm really lucky and thankful you saw this.

I'm willing to do anything further I can to help.

**Comment by nodkz** [comment]
`Graphql-compose` does not freeze types internally. How I know `graphql-js` also does not freeze type objects. 

It looks like `babel` freeze **default export** object. This is correct behavior, cause modules export should not be extended. V8 provides runtime performance optimizations when objects are frozen. That's why, how I think, exported schema became not operable with `graphql-extensions`.

So do not pass schema as a default export.
```js
// file1
export const mySchema = ...;

// file2
import { mySchema } from './file1';
```

**Comment by the-simian** [comment]
Thanks @nodkz , that's probably my issue, and something I hadn't considered. I'll close this, I sincerely appreciate all the help.

**Comment by jdalton** [comment]
Hiya!

Babel doesn't freeze default export objects but `@std/esm` will seal namespace objects as well as the `module.exports` of any bridged ESM modules.

**Comment by jdalton** [comment]
I'll ping your DMs to dig more into usage.
